### ISSUE TITLE
Mis-use of Internal IP addresses

### ISSUE THREAD

**Issue by wvdvegt** [RotaruDan/test-users#78] opened 2015-11-26 09:09 UTC
Hi

We're still trying to get the rage tracker working but still have issues with it. 

It seems when we open the login page (at port 3350) from a webbrowser on an external machine and just wait.

We then get what it seems to be an Ajax related error message after 30 seconds (a timeout) because the browser page tries to connect to a internal address on the server (see screenshot, the APIPATH and PROXY settings both start with 172.17.0.8). 

This address off-course can NEVER work from an external browser and but will happily pass testing if everything is performed locally on the server.

![snip_20151126095349](https://cloud.githubusercontent.com/assets/1768983/11418823/b70907c6-9423-11e5-9c66-4603dd1f6d82.png)

**Comment by wvdvegt** [comment] 2015-11-26 09:12
Another screen-shot from a Windows machine clearly shows the webbrowser making a call to a linux/docker internal & non routable IP address starting with 172.17.0 (rest was clipped).

![snip_20151126100649](https://cloud.githubusercontent.com/assets/1768983/11419166/dd7e4b30-9425-11e5-9621-c16407f0ff15.png)

**Comment by manuel-freire** [comment] 2015-11-26 16:07
This should be fixed - can you try it again? 

Our new solution: whatever IP is used to access the front-end will be used to access A2 (from the front-end). This avoids having to configure the front-end to use a particular external IP, which would be hard to discover from within.

**Closed as completed by manuel-freire** 2015-11-26 16:07 UTC

**Comment by wvdvegt** [comment] 2015-11-27 09:27
Hi Manual, 

We re-installed just before i posted this issue. Was it fixed after this?

**Comment by manuel-freire** [comment] 2015-11-27 13:44
I certainly cannot reproduce the problem now, so I mus assume that it is now fixed.

**Comment by wvdvegt** [comment] 2015-11-27 13:58
Hi Manuel,

We’ll checkout the new install when Mat is back (will the Tuesday I guess).

23 hours ago is just after our last attempt to re-install.

Best Regards
Wim van der Vegt

**Comment by wvdvegt** [comment] 2015-11-27 14:08
The issue is that there are two files in the front-end repo:

env-vars.js (causes problems)
env-vars-example.js (is ok)

But we have the impression that the install from yesterday still used the end-vars,js.

Btw the naming of the 2nd file is strange (normally an example file like this should be copied manually somewhere after an install).

Best Regards
Wim van der Vegt

**Comment by manuel-freire** [comment] 2015-11-27 16:12
Note that those files are overwritten with the environment variables found when the application is launched (see  [front's app/config-values.js](https://github.com/e-ucm/rage-analytics-frontend/blob/master/app/config-values.js#L37) - similar files exist in a2 and back), taking their values from [rage-analytics' environment stanzas](https://github.com/e-ucm/rage-analytics/blob/master/docker-compose.yml)

**Comment by wvdvegt** [comment] 2015-11-27 16:51
Hi Manual

So do we need to set environment variables in Linux before installing? If so we didn't spot that in the manual.

Or are values from the docker yml scripts used (in which case we have a problem because those are downloaded from the repo during install).

Best Regards
Wim van der Vegt

**Comment by manuel-freire** [comment] 2015-12-09 17:02
The docker-compose.yml `environment:` stanzas are used by docker-compose to set the environment values that are passed on to the different docker containers. No environment variables need to be set in Linux. 

While we provide environment-variable values that are tested to work, you can easily tweak those values. They will be overwritten if you perform a new install - so you must manually back-up any changes and then re-apply them after each new install (or use the mechanism described [here](https://docs.docker.com/compose/extends/) - essentially, put your changes into a `docker-compose.override.yml` file). However, we understand that once you are customizing your deployments, this level of awareness is not much of an extra burden. Predicting what changes users are likely to make and ensuring that they do not break anything is out-of-scope for our installation scripts.

Please open new issues for new problems - the original problem (issue) due to internal port use has long been solved, and I missed this message for a long time due to the issue officially being "closed" (as the original problem is solved).
